name: Build and Release

on:
  push:
    branches:
      - master
      - "feature/*"
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: '11'

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Create Release and Upload APK
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            New release for branch/tag: ${{ github.ref }}
        if: startsWith(github.ref, 'refs/tags/')

        # Download the APK artifact
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app-debug
          path: /tmp

        # Upload the downloaded APK as release asset
      - name: Upload Release APK
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: /tmp/app-debug.apk
          asset_name: app-debug-${{ github.ref }}.apk
          asset_content_type: application/vnd.android.package-archive
